---

- name: Installing PHP5 and its dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Installing PHP5 and its dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - php
    - php-mysql
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Creating Demo PHP Page
  state: present
  create: true
  dest: /var/www/info.php
  mode: 0664
  blockinfile: |
    <?php
    phpinfo();
    ?>
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - restart apache

- name: Creating Demo PHP Page
  state: present
  create: true
  dest: /var/www/html/info.php
  mode: 0664
  blockinfile: |
    <?php
    phpinfo();
    ?>
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  notify:
    - restart httpd
