---

- name: Installing PHP5 and its dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt

- name: Creating Demo PHP Page
  state: present
  create: true
  dest: /var/www/info.php
  mode: 0664
  blockinfile: |
    <?php
    phpinfo();
    ?>
  notify:
    - restart apache
