---

- name: Production Setting to Sysctl Config
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: 'net.core.rmem_max', value: '16777216' }
    - { name: 'net.core.wmem_max', value: '16777216' }
    - { name: 'net.core.rmem_default', value: '16777216' }
    - { name: 'net.core.wmem_default', value: '16777216' }
    - { name: 'net.core.optmem_max', value: '40960' }
    - { name: 'net.ipv4.tcp_rmem', value: '4096 87380 16777216' }
    - { name: 'net.ipv4.tcp_wmem', value: '4096 65536 16777216' }
    - { name: 'vm.max_map_count', value: '1048575'}
    - { name: 'vm.swappiness', value:'1'}
