---

- name: Adding Key for Docker
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Adding docker source list
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
    update_cache: true
    filename: 'docker'

- name: Installing docker and dependenices
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - docker-engine
    - python-pip

- name: Ensure docker is Running
  service:
    name: docker
    state: started
    enabled: true

- name: Creating Docker Group
  group:
    name: docker
    state: present

- name: Installing Docker Compose and dependenices
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - docker-compose
