---
- include: bootstrap.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: postgres_ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: postgres_redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
