---

- name: Installing latest epel-release-7.8
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
    state: present
    update_cache: true

- name: Installing R
  yum:
    name: R
    state: present

- name: Installing Rstudio
  yum:
    name: https://download2.rstudio.org/rstudio-server-rhel-1.0.136-x86_64.rpm
    state: present
    disable_gpg_check: false
