---

# wget --no-cookies --no-check-certificate
# --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
# "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm"

# - name: Downloading Oracle Java 7
#   uri:
#     url: "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm"
#     method: GET
#     validate_certs: false
#     header:
#       - "Cookie:oraclelicense=accept-securebackup-cookie"
#     dest: /tmp/oracle.rpm
#     creates: /tmp/oracle.rpm
#
# - name: Downloading Oracle Java 8
#   uri:
#     url: "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jre-7u79-linux-x64.rpm"
#     method: GET
#     validate_certs: false
#     header:
#       - "Cookie:oraclelicense=accept-securebackup-cookie"
#     dest: /tmp/oracle.rpm
#     creates: /tmp/oracle.rpm

- name: Installing Oracle {{ java_version }}
  yum:
    name: /tmp/oracle.rpm
    state: present

# - include: java_home.yml
