---

- include: bootstrap.yml
  when: ansible_os_family == 'Debian'

- include: mysql_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include: mysql_redhat.yml
  when: ansible_os_family == 'RedHat'
