---

- name: Copying Latest yum config to System
  copy:
    src: mysql57-community-release-el7-9.noarch.rpm
    dest: /tmp/mysql57-community-release-el7-9.noarch.rpm

- name: Installing Latest APT config for mysql-server
  yum:
    name: /tmp/mysql57-community-release-el7-9.noarch.rpm
    update_cache: true

- name: Install MySQL-Serve
  yum: package={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user=root

- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ MySQL_root_pass }}" login_user=root
