---

- name: Installing Latest APT config for mysql-server
  apt:
    deb: http://repo.mysql.com//mysql-apt-config_0.8.1-1_all.deb
    update_cache: true

- name: Install MySQL
  apt:
    name: "{{ item }}"
    state:  present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Ensure mysql-server is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state:  absent
    login_password: "{{ MySQL_root_pass }}"
    login_user: root

- name: Set root password
  mysql_user:
    user: root
    password: "{{ MySQL_root_pass }}"
    host: "{{ item }}"
    login_password: "{{ MySQL_root_pass }}"
    login_user: root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_password: "{{ MySQL_root_pass }}"
    login_user: root
