---
- name: Creating Service for Tomcat
  blockinfile:
    dest: /etc/systemd/system/tomcat.service
    mode: 0777
    owner: root
    group: root
    create: true
    block: |
    # Systemd unit file for tomcat
    [Unit]
    Description=Apache Tomcat Web Application Container
    After=syslog.target network.target

    [Service]
    Type=forking

    Environment=CATALINA_PID=/usr/share/tomcat/tomcat.pid
    Environment=CATALINA_HOME=/usr/share/tomcat
    Environment=CATALINA_BASE=/usr/share/tomcat
    Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
    Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

    ExecStart=/usr/share/tomcat/bin/startup.sh
    ExecStop=/bin/kill -15 $MAINPID

    User=tomcat
    Group=tomcat
    UMask=0007
    RestartSec=10
    Restart=always

    [Install]
    WantedBy=multi-user.target


- name: Reloading Systemd Deamon
  systemd:
    name: tomcat
    daemon_reload: yes
