---

- name: Adding tomcat group
  group:
    name: tomcat
    state: present

- name: Adding tomcat user
  user:
    name: tomcat
    state: present
    group: tomcat

- name: Making Installation Directory for Tomcat Server
  file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Downloading and Extracting Tomcat Server | 8
  unarchieve:
    src:  http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
    dest: /usr/share/tomcat
    create: /usr/share/tomcat/bin
    owner: tomcat
    group: tomcat
    remote_src: true
    extra_opts: ["--strip-components=1"]

- include: systemd.yml

- name: Creating default user admin
  blockinfile:
    dest: /usr/share/tomcat/conf/tomcat-users.xml
    create: true
    block: |
    <tomcat-users>
    <user username="admin" password="{{ tomcat_admin_pass }}" roles="manager-gui,admin-gui"/>
    </tomcat-users>
  notify:
    - restart tomcat
